name: Deploy and Merge to Main

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

# Define permissions required for workflow actions
permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages and Merge to Main
    runs-on: ubuntu-latest
    steps:
      # Check out the repository content
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      # Install project dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build the Docusaurus website
      - name: Build website
        run: yarn build

      # Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      # Merge the gh-pages branch back into the main branch after successful deployment
      - name: Merge gh-pages to main
        if: success() && github.ref == 'refs/heads/main' # Run only on successful deployment to main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

          git checkout main
          git merge --no-ff --no-edit gh-pages
          git push origin main
